[package]
name = "crypto-key-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
pbkdf2 = { version = "0.12", default-features = false, features = ["hmac"] }
hmac = "0.12"

[dev-dependencies]
hex = "0.4"
