[package]
name = "crypto-key-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
# Using std library only for base commit
# Future PRs will add crypto dependencies when network allows

[dev-dependencies]

